### ISSUE TITLE
a map that includes both SCI & JLDP as well as Pt Conception State Marine Reserve 8/16

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/jldp_maprequests#5]
a map that includes both SCI & JLDP as well as Pt Conception State Marine Reserve.

**Comment by bcohen27** [comment]
Made an mxd (sba_Dangermond_Preserve_Map_with_SCI 20180814) in Central_Coast\Projects\Sba\Sites\BRSB_Confidential\Mxds that is a copy of sba_Dangermond_Preserve_Map_20180410 and extended the inset map south to include the channel islands and labeled Santa Cruz Island. Wanted to see their proximity. Created a pdf in the Plots folder.

**Comment by megrwebb** [comment]
Awesome.  It looks like you are missing some of the fonts I used, but that's minor.  What is this map for (i.e. use case)?  I have a map draft for TNC Mag that includes all these features.

**Comment by megrwebb** [comment]
Ah, I scrolled down to the bottom of the email...for a donor trip.

**Comment by megrwebb** [comment]
Hey @bcohen27 let me know if the map revision you made will work for this request or if something else is still needed.

**Comment by bcohen27** [comment]
Waiting on feedback, unknown as to timeline on that.
