### ISSUE TITLE
Mapping Sensitive Areas (finals ready for 9/6 meeting)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/jldp_maprequests#6]
As Powerpoint slide-sized maps

All sensitive areas as red

then individual maps of
animals
plants
vegetation
hydrology
critical habitats
cultural

List of layers to use:
AQUATIC - Springs (CMR 2012)
AQUATIC - Wetlands and Waters (A&M 2013)
AQUATIC - Streams (A&M 2013)
BUILDINGS - Cojo & Jalama Ranch HQ Buildings
GEOLOGY - Landslides (EnGeo 2011)
RANCHING AG - Historic Farming Areas (PACE 2012)
VEGETATION - Rare Plant Points (WRA 2012)
VEGETATION - Rare Plant Polygons (WRA 2012)
VEGETATION - CNDDB Botany (CDFW 2017)
VEGETATION - Sensitive Vegetation Communities (WRA 2012)
WILDLIFE - Critical Habitat Wildlife Polygons (USFWS 2017)
WILDLIFE - California red-legged frog habitat (WRA 2012)
WILDLIFE - California red-legged frog habitat 300ft Buffer (WRA 2012)
WILDLIFE - Tidewater Goby Habitat (WRA 2012)
WILDLIFE - American Badger (WRA 2012)
WILDLIFE - Birds (WRA 2012)
WILDLIFE - Bats (WRA 2012)
WILDLIFE - Reptiles and Amphibians (WRA 2012)
WILDLIFE - Marine Mammals (WRA 2012)
WILDLIFE - CNDDB Wildlife (CDFW 2017)
WILDLIFE - Critical Habitat Wildlife Lines (USFWS 2017)
WILDLIFE - Critical Habitat Wildlife Polygons (USFWS 2017)

**Comment by megrwebb** [comment]
@connorshank let's meet later this week to go over this mapping request.  I'll look for some time on your calendar.  Thanks!

**Comment by megrwebb** [comment]
Hi @connorshank and @bcohen27 .  It sounds like you both are directly coordinating on this request.  I think that makes the most sense, but of course I'm here to support/advise as needed.
